- name: make symlinks for Recon tv repos
  become_user: ldraney
  file:
    src: /mnt/hgfs/VMShare/Recon
    dest: /home/ldraney/recon
    state: link

#- name: mkdir for recon 
  #become_user: ldraney
  #file:
    #path: /home/ldraney/recon/tv/
    ##type: dir
    #state: directory

- name: Ubuntu 2204 needs this to have same key type as old Recon Git server
  lineinfile:
    insertafter: EOF
    state: present
    line: '    PubkeyAcceptedKeyTypes +ssh-rsa'
    path: /etc/ssh/ssh_config

