
- name: copy wallpaper file
  copy: 
    src: look/backgroundFiles/wallpaper.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root
  
- name: set wallpaper
  become_user: ldraney
  dconf: 
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: ldraney
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: change login background image
  ansible.builtin.copy:
    src: '/home/ldraney/github/ansible_desktop_setup/look/backgroundFiles/login.jpg'
    dest: '/usr/share/backgrounds/pia21972.png'
    mode: '0644'

- name: add symlink to regolith theme
  file:
    state: link
    owner: root
    group: root
    follow: false
    #owner: ldraney
    #group: ldraney
    src: '/home/ldraney/github/ansible_desktop_setup/look/gruvboxCustom'
    dest: '/usr/share/regolith-look/gruvboxCustom'
#- name: add symlink to regolith theme
  #copy:
    #src: '/home/ldraney/github/ansible_desktop_setup/look'
    #dest: '/usr/share/regolith-look/gruvboxCustom'

- name: regolith-look commands
  become_user: ldraney
  ignore_errors: yes
  shell:
    #cmd: regolith-look set gruvboxCustom
    cmd: '{{ item }}'
    #cmd: regolith-look set gruvboxCustom
  loop:
    - regolith-look set gruvboxCustom

- name: configure dconf for gray comments and transparent background
  become_user: ldraney
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:5a51ec6d-9841-432b-b134-ad902343b49c/{{ item.profile }}"
    value: '{{ item.value }}'
    #state: present
  loop:
    - { profile: 'use-transparent-background', value: 'true' }
    - { profile: 'background-transparency-percent', value: '18' }
