
- name: copy wallpaper file
  copy: 
    src: look/backgroundFiles/wallpaper.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root
  
- name: set wallpaper
  become_user: ldraney
  dconf: 
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: ldraney
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: change login background image
  ansible.builtin.copy:
    src: '/home/ldraney/github/ansible_desktop_setup/look/backgroundFiles/login.jpg'
    dest: '/usr/share/backgrounds/pia21972.png'
    mode: '0644'

- name: add symlink to regolith theme
  file:
    state: link
    owner: root
    group: root
    #owner: ldraney
    #follow: false
    #group: ldraney
    src: '/home/ldraney/github/ansible_desktop_setup/look'
    dest: '/usr/share/regolith-look/gruvboxCustom'

- name: regolith-look command
  become_user: ldraney
  shell:
    cmd: regolith-look set gruvboxCustom

